# Generated by Django 5.1.3 on 2024-12-30 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='carousel_banners/')),
                ('link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Genre', models.TextField(max_length=255)),
                ('availability', models.TextField(max_length=255, null=True)),
                ('rating', models.TextField(max_length=255, null=True)),
                ('plays', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('type', models.CharField(max_length=254)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('permissions', models.JSONField(default=dict)),
                ('access_all_venues', models.BooleanField(default=False)),
                ('access_all_games', models.BooleanField(default=False)),
                ('games', models.ManyToManyField(blank=True, related_name='roles', to='myapp.games')),
                ('user', models.ManyToManyField(through='myapp.Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.role'),
        ),
        migrations.CreateModel(
            name='TicketNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.TextField(max_length=255)),
                ('hours', models.TextField(max_length=255)),
                ('specialevent', models.TextField(max_length=255, null=True)),
                ('status', models.TextField(max_length=255, null=True)),
                ('locationdefine', models.TextField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('games', models.ManyToManyField(related_name='venues', to='myapp.games')),
                ('tickets', models.ManyToManyField(blank=True, related_name='venue_tickets', to='myapp.tickets')),
            ],
        ),
        migrations.AddField(
            model_name='tickets',
            name='venues',
            field=models.ManyToManyField(related_name='ticket_venues', to='myapp.venues'),
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('modelNo', models.CharField(max_length=245, unique=True)),
                ('serialNo', models.CharField(max_length=245, unique=True)),
                ('barcodeNo', models.IntegerField(unique=True)),
                ('assignedVenue', models.CharField(max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.venues')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='roles', to='myapp.venues'),
        ),
        migrations.AddField(
            model_name='profile',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='myapp.venues'),
        ),
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('modelNo', models.CharField(max_length=245, unique=True)),
                ('serialNo', models.CharField(max_length=245, unique=True)),
                ('barcodeNo', models.IntegerField(unique=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.venues')),
            ],
        ),
    ]
