# Generated by Django 5.1.3 on 2025-01-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_headset_password_tablet_password_room_headset_room_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselBanner',
        ),
        migrations.RemoveField(
            model_name='venues',
            name='games',
        ),
        migrations.RemoveField(
            model_name='role',
            name='games',
        ),
        migrations.RemoveField(
            model_name='headset',
            name='room',
        ),
        migrations.RemoveField(
            model_name='headset',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='venues',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.RemoveField(
            model_name='role',
            name='venues',
        ),
        migrations.RemoveField(
            model_name='room',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='room',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='ticketnotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='venues',
        ),
        migrations.RemoveField(
            model_name='venues',
            name='tickets',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.DeleteModel(
            name='Headset',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Tablet',
        ),
        migrations.DeleteModel(
            name='TicketNotification',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.DeleteModel(
            name='Venues',
        ),
    ]
