# Generated by Django 5.1.3 on 2025-01-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_carouselbanner_remove_venues_games_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabletserialNo', models.CharField(max_length=255)),
                ('ticket_id', models.IntegerField()),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.CharField(max_length=255)),
            ],
        ),
    ]
